export const GET_PRODUCTS_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_CART = "GET_CART";
export const ADD_PRODUCT_CART = "ADD_PRODUCT_CART";
export const UPDATE_CART = "UPDATE_CART";
export const REMOVE_PRODUCT_CART = "REMOVE_PRODUCT_CART";
export const SET_SORT_TYPE = 'SET_SORT_TYPE';
export const SEARCH = 'SEARCH';
export const SET_FILTER_TYPE = 'SET_FILTER_TYPE';